/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { ApiRequestBuilderNavigationMetadata, ApiRequestBuilderRequestsMetadata, type ApiRequestBuilder } from './api/index.js';
// @ts-ignore
import { ApisRequestBuilderNavigationMetadata, ApisRequestBuilderRequestsMetadata, type ApisRequestBuilder } from './apis/index.js';
// @ts-ignore
import { LogsRequestBuilderNavigationMetadata, LogsRequestBuilderRequestsMetadata, type LogsRequestBuilder } from './logs/index.js';
// @ts-ignore
import { OpenidRequestBuilderNavigationMetadata, type OpenidRequestBuilder } from './openid/index.js';
// @ts-ignore
import { type VersionRequestBuilder, VersionRequestBuilderRequestsMetadata } from './version/index.js';
// @ts-ignore
import { type WellKnownRequestBuilder, WellKnownRequestBuilderNavigationMetadata } from './wellKnown/index.js';
// @ts-ignore
import { apiClientProxifier, registerDefaultDeserializer, registerDefaultSerializer, type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type RequestAdapter } from '@microsoft/kiota-abstractions';
// @ts-ignore
import { FormParseNodeFactory, FormSerializationWriterFactory } from '@microsoft/kiota-serialization-form';
// @ts-ignore
import { JsonParseNodeFactory, JsonSerializationWriterFactory } from '@microsoft/kiota-serialization-json';
// @ts-ignore
import { MultipartSerializationWriterFactory } from '@microsoft/kiota-serialization-multipart';
// @ts-ignore
import { TextParseNodeFactory, TextSerializationWriterFactory } from '@microsoft/kiota-serialization-text';

/**
 * Instantiates a new {@link KubeApi_ts} and sets the default values.
 * @param requestAdapter The request adapter to use to execute the requests.
 */
// @ts-ignore
export function createKubeApi_ts(requestAdapter: RequestAdapter) {
    registerDefaultSerializer(JsonSerializationWriterFactory);
    registerDefaultSerializer(TextSerializationWriterFactory);
    registerDefaultSerializer(FormSerializationWriterFactory);
    registerDefaultSerializer(MultipartSerializationWriterFactory);
    registerDefaultDeserializer(JsonParseNodeFactory);
    registerDefaultDeserializer(TextParseNodeFactory);
    registerDefaultDeserializer(FormParseNodeFactory);
    const pathParameters: Record<string, unknown> = {
        "baseurl": requestAdapter.baseUrl,
    };
    return apiClientProxifier<KubeApi_ts>(requestAdapter, pathParameters, KubeApi_tsNavigationMetadata, undefined);
}
/**
 * The main entry point of the SDK, exposes the configuration and the fluent API.
 */
export interface KubeApi_ts extends BaseRequestBuilder<KubeApi_ts> {
    /**
     * The api property
     */
    get api(): ApiRequestBuilder;
    /**
     * The apis property
     */
    get apis(): ApisRequestBuilder;
    /**
     * The logs property
     */
    get logs(): LogsRequestBuilder;
    /**
     * The openid property
     */
    get openid(): OpenidRequestBuilder;
    /**
     * The version property
     */
    get version(): VersionRequestBuilder;
    /**
     * The wellKnown property
     */
    get wellKnown(): WellKnownRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const KubeApi_tsUriTemplate = "{+baseurl}";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const KubeApi_tsNavigationMetadata: Record<Exclude<keyof KubeApi_ts, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    api: {
        requestsMetadata: ApiRequestBuilderRequestsMetadata,
        navigationMetadata: ApiRequestBuilderNavigationMetadata,
    },
    apis: {
        requestsMetadata: ApisRequestBuilderRequestsMetadata,
        navigationMetadata: ApisRequestBuilderNavigationMetadata,
    },
    logs: {
        requestsMetadata: LogsRequestBuilderRequestsMetadata,
        navigationMetadata: LogsRequestBuilderNavigationMetadata,
    },
    openid: {
        navigationMetadata: OpenidRequestBuilderNavigationMetadata,
    },
    version: {
        requestsMetadata: VersionRequestBuilderRequestsMetadata,
    },
    wellKnown: {
        navigationMetadata: WellKnownRequestBuilderNavigationMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
