/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { CertificatesigningrequestsRequestBuilderNavigationMetadata, CertificatesigningrequestsRequestBuilderRequestsMetadata, type CertificatesigningrequestsRequestBuilder } from './certificatesigningrequests/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /apis/certificates.k8s.io/v1/watch
 */
export interface WatchRequestBuilder extends BaseRequestBuilder<WatchRequestBuilder> {
    /**
     * The certificatesigningrequests property
     */
    get certificatesigningrequests(): CertificatesigningrequestsRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const WatchRequestBuilderUriTemplate = "{+baseurl}/apis/certificates.k8s.io/v1/watch";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const WatchRequestBuilderNavigationMetadata: Record<Exclude<keyof WatchRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    certificatesigningrequests: {
        requestsMetadata: CertificatesigningrequestsRequestBuilderRequestsMetadata,
        navigationMetadata: CertificatesigningrequestsRequestBuilderNavigationMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
