/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { CsistoragecapacitiesRequestBuilderNavigationMetadata, CsistoragecapacitiesRequestBuilderRequestsMetadata, type CsistoragecapacitiesRequestBuilder } from './csistoragecapacities/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /apis/storage.k8s.io/v1/watch/namespaces/{namespace}
 */
export interface WithNamespaceItemRequestBuilder extends BaseRequestBuilder<WithNamespaceItemRequestBuilder> {
    /**
     * The csistoragecapacities property
     */
    get csistoragecapacities(): CsistoragecapacitiesRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const WithNamespaceItemRequestBuilderUriTemplate = "{+baseurl}/apis/storage.k8s.io/v1/watch/namespaces/{namespace}";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const WithNamespaceItemRequestBuilderNavigationMetadata: Record<Exclude<keyof WithNamespaceItemRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    csistoragecapacities: {
        requestsMetadata: CsistoragecapacitiesRequestBuilderRequestsMetadata,
        navigationMetadata: CsistoragecapacitiesRequestBuilderNavigationMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
