/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { ApiservicesRequestBuilderNavigationMetadata, ApiservicesRequestBuilderRequestsMetadata, type ApiservicesRequestBuilder } from './apiservices/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /apis/apiregistration.k8s.io/v1/watch
 */
export interface WatchRequestBuilder extends BaseRequestBuilder<WatchRequestBuilder> {
    /**
     * The apiservices property
     */
    get apiservices(): ApiservicesRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const WatchRequestBuilderUriTemplate = "{+baseurl}/apis/apiregistration.k8s.io/v1/watch";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const WatchRequestBuilderNavigationMetadata: Record<Exclude<keyof WatchRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    apiservices: {
        requestsMetadata: ApiservicesRequestBuilderRequestsMetadata,
        navigationMetadata: ApiservicesRequestBuilderNavigationMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
