/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { ConfigmapsRequestBuilderRequestsMetadata, type ConfigmapsRequestBuilder } from './configmaps/index.js';
// @ts-ignore
import { EndpointsRequestBuilderRequestsMetadata, type EndpointsRequestBuilder } from './endpoints/index.js';
// @ts-ignore
import { EventsRequestBuilderRequestsMetadata, type EventsRequestBuilder } from './events/index.js';
// @ts-ignore
import { LimitrangesRequestBuilderRequestsMetadata, type LimitrangesRequestBuilder } from './limitranges/index.js';
// @ts-ignore
import { NamespacesRequestBuilderNavigationMetadata, NamespacesRequestBuilderRequestsMetadata, type NamespacesRequestBuilder } from './namespaces/index.js';
// @ts-ignore
import { NodesRequestBuilderNavigationMetadata, NodesRequestBuilderRequestsMetadata, type NodesRequestBuilder } from './nodes/index.js';
// @ts-ignore
import { PersistentvolumeclaimsRequestBuilderRequestsMetadata, type PersistentvolumeclaimsRequestBuilder } from './persistentvolumeclaims/index.js';
// @ts-ignore
import { PersistentvolumesRequestBuilderNavigationMetadata, PersistentvolumesRequestBuilderRequestsMetadata, type PersistentvolumesRequestBuilder } from './persistentvolumes/index.js';
// @ts-ignore
import { PodsRequestBuilderRequestsMetadata, type PodsRequestBuilder } from './pods/index.js';
// @ts-ignore
import { PodtemplatesRequestBuilderRequestsMetadata, type PodtemplatesRequestBuilder } from './podtemplates/index.js';
// @ts-ignore
import { ReplicationcontrollersRequestBuilderRequestsMetadata, type ReplicationcontrollersRequestBuilder } from './replicationcontrollers/index.js';
// @ts-ignore
import { ResourcequotasRequestBuilderRequestsMetadata, type ResourcequotasRequestBuilder } from './resourcequotas/index.js';
// @ts-ignore
import { SecretsRequestBuilderRequestsMetadata, type SecretsRequestBuilder } from './secrets/index.js';
// @ts-ignore
import { ServiceaccountsRequestBuilderRequestsMetadata, type ServiceaccountsRequestBuilder } from './serviceaccounts/index.js';
// @ts-ignore
import { ServicesRequestBuilderRequestsMetadata, type ServicesRequestBuilder } from './services/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/v1/watch
 */
export interface WatchRequestBuilder extends BaseRequestBuilder<WatchRequestBuilder> {
    /**
     * The configmaps property
     */
    get configmaps(): ConfigmapsRequestBuilder;
    /**
     * The endpoints property
     */
    get endpoints(): EndpointsRequestBuilder;
    /**
     * The events property
     */
    get events(): EventsRequestBuilder;
    /**
     * The limitranges property
     */
    get limitranges(): LimitrangesRequestBuilder;
    /**
     * The namespaces property
     */
    get namespaces(): NamespacesRequestBuilder;
    /**
     * The nodes property
     */
    get nodes(): NodesRequestBuilder;
    /**
     * The persistentvolumeclaims property
     */
    get persistentvolumeclaims(): PersistentvolumeclaimsRequestBuilder;
    /**
     * The persistentvolumes property
     */
    get persistentvolumes(): PersistentvolumesRequestBuilder;
    /**
     * The pods property
     */
    get pods(): PodsRequestBuilder;
    /**
     * The podtemplates property
     */
    get podtemplates(): PodtemplatesRequestBuilder;
    /**
     * The replicationcontrollers property
     */
    get replicationcontrollers(): ReplicationcontrollersRequestBuilder;
    /**
     * The resourcequotas property
     */
    get resourcequotas(): ResourcequotasRequestBuilder;
    /**
     * The secrets property
     */
    get secrets(): SecretsRequestBuilder;
    /**
     * The serviceaccounts property
     */
    get serviceaccounts(): ServiceaccountsRequestBuilder;
    /**
     * The services property
     */
    get services(): ServicesRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const WatchRequestBuilderUriTemplate = "{+baseurl}/api/v1/watch";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const WatchRequestBuilderNavigationMetadata: Record<Exclude<keyof WatchRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    configmaps: {
        requestsMetadata: ConfigmapsRequestBuilderRequestsMetadata,
    },
    endpoints: {
        requestsMetadata: EndpointsRequestBuilderRequestsMetadata,
    },
    events: {
        requestsMetadata: EventsRequestBuilderRequestsMetadata,
    },
    limitranges: {
        requestsMetadata: LimitrangesRequestBuilderRequestsMetadata,
    },
    namespaces: {
        requestsMetadata: NamespacesRequestBuilderRequestsMetadata,
        navigationMetadata: NamespacesRequestBuilderNavigationMetadata,
    },
    nodes: {
        requestsMetadata: NodesRequestBuilderRequestsMetadata,
        navigationMetadata: NodesRequestBuilderNavigationMetadata,
    },
    persistentvolumeclaims: {
        requestsMetadata: PersistentvolumeclaimsRequestBuilderRequestsMetadata,
    },
    persistentvolumes: {
        requestsMetadata: PersistentvolumesRequestBuilderRequestsMetadata,
        navigationMetadata: PersistentvolumesRequestBuilderNavigationMetadata,
    },
    pods: {
        requestsMetadata: PodsRequestBuilderRequestsMetadata,
    },
    podtemplates: {
        requestsMetadata: PodtemplatesRequestBuilderRequestsMetadata,
    },
    replicationcontrollers: {
        requestsMetadata: ReplicationcontrollersRequestBuilderRequestsMetadata,
    },
    resourcequotas: {
        requestsMetadata: ResourcequotasRequestBuilderRequestsMetadata,
    },
    secrets: {
        requestsMetadata: SecretsRequestBuilderRequestsMetadata,
    },
    serviceaccounts: {
        requestsMetadata: ServiceaccountsRequestBuilderRequestsMetadata,
    },
    services: {
        requestsMetadata: ServicesRequestBuilderRequestsMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
