/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { ControllerrevisionsRequestBuilderRequestsMetadata, type ControllerrevisionsRequestBuilder } from './controllerrevisions/index.js';
// @ts-ignore
import { DaemonsetsRequestBuilderRequestsMetadata, type DaemonsetsRequestBuilder } from './daemonsets/index.js';
// @ts-ignore
import { DeploymentsRequestBuilderRequestsMetadata, type DeploymentsRequestBuilder } from './deployments/index.js';
// @ts-ignore
import { NamespacesRequestBuilderNavigationMetadata, type NamespacesRequestBuilder } from './namespaces/index.js';
// @ts-ignore
import { ReplicasetsRequestBuilderRequestsMetadata, type ReplicasetsRequestBuilder } from './replicasets/index.js';
// @ts-ignore
import { StatefulsetsRequestBuilderRequestsMetadata, type StatefulsetsRequestBuilder } from './statefulsets/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /apis/apps/v1/watch
 */
export interface WatchRequestBuilder extends BaseRequestBuilder<WatchRequestBuilder> {
    /**
     * The controllerrevisions property
     */
    get controllerrevisions(): ControllerrevisionsRequestBuilder;
    /**
     * The daemonsets property
     */
    get daemonsets(): DaemonsetsRequestBuilder;
    /**
     * The deployments property
     */
    get deployments(): DeploymentsRequestBuilder;
    /**
     * The namespaces property
     */
    get namespaces(): NamespacesRequestBuilder;
    /**
     * The replicasets property
     */
    get replicasets(): ReplicasetsRequestBuilder;
    /**
     * The statefulsets property
     */
    get statefulsets(): StatefulsetsRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const WatchRequestBuilderUriTemplate = "{+baseurl}/apis/apps/v1/watch";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const WatchRequestBuilderNavigationMetadata: Record<Exclude<keyof WatchRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    controllerrevisions: {
        requestsMetadata: ControllerrevisionsRequestBuilderRequestsMetadata,
    },
    daemonsets: {
        requestsMetadata: DaemonsetsRequestBuilderRequestsMetadata,
    },
    deployments: {
        requestsMetadata: DeploymentsRequestBuilderRequestsMetadata,
    },
    namespaces: {
        navigationMetadata: NamespacesRequestBuilderNavigationMetadata,
    },
    replicasets: {
        requestsMetadata: ReplicasetsRequestBuilderRequestsMetadata,
    },
    statefulsets: {
        requestsMetadata: StatefulsetsRequestBuilderRequestsMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
