/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createListMetaFromDiscriminatorValue, createObjectMetaFromDiscriminatorValue, serializeListMeta, serializeObjectMeta, type ListMeta, type ObjectMeta } from '../../../apimachinery/pkg/apis/meta/v1/index.js';
// @ts-ignore
import { type AdditionalDataHolder, type Parsable, type ParseNode, type SerializationWriter } from '@microsoft/kiota-abstractions';

/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {PriorityClass}
 */
// @ts-ignore
export function createPriorityClassFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoPriorityClass;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {PriorityClassList}
 */
// @ts-ignore
export function createPriorityClassListFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoPriorityClassList;
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoPriorityClass(priorityClass: Partial<PriorityClass> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "apiVersion": n => { priorityClass.apiVersion = n.getStringValue(); },
        "description": n => { priorityClass.description = n.getStringValue(); },
        "globalDefault": n => { priorityClass.globalDefault = n.getBooleanValue(); },
        "kind": n => { priorityClass.kind = n.getStringValue(); },
        "metadata": n => { priorityClass.metadata = n.getObjectValue<ObjectMeta>(createObjectMetaFromDiscriminatorValue); },
        "preemptionPolicy": n => { priorityClass.preemptionPolicy = n.getStringValue(); },
        "value": n => { priorityClass.value = n.getNumberValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoPriorityClassList(priorityClassList: Partial<PriorityClassList> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "apiVersion": n => { priorityClassList.apiVersion = n.getStringValue(); },
        "items": n => { priorityClassList.items = n.getCollectionOfObjectValues<PriorityClass>(createPriorityClassFromDiscriminatorValue); },
        "kind": n => { priorityClassList.kind = n.getStringValue(); },
        "metadata": n => { priorityClassList.metadata = n.getObjectValue<ListMeta>(createListMetaFromDiscriminatorValue); },
    }
}
/**
 * PriorityClass defines mapping from a priority class name to the priority integer value. The value can be any valid integer.
 */
export interface PriorityClass extends AdditionalDataHolder, Parsable {
    /**
     * Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
     */
    additionalData?: Record<string, unknown>;
    /**
     * APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
     */
    apiVersion?: string | null;
    /**
     * description is an arbitrary string that usually provides guidelines on when this priority class should be used.
     */
    description?: string | null;
    /**
     * globalDefault specifies whether this PriorityClass should be considered as the default priority for pods that do not have any priority class. Only one PriorityClass can be marked as `globalDefault`. However, if more than one PriorityClasses exists with their `globalDefault` field set to true, the smallest value of such global default PriorityClasses will be used as the default priority.
     */
    globalDefault?: boolean | null;
    /**
     * Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
     */
    kind?: string | null;
    /**
     * ObjectMeta is metadata that all persisted resources must have, which includes all objects users must create.
     */
    metadata?: ObjectMeta | null;
    /**
     * preemptionPolicy is the Policy for preempting pods with lower priority. One of Never, PreemptLowerPriority. Defaults to PreemptLowerPriority if unset.
     */
    preemptionPolicy?: string | null;
    /**
     * value represents the integer value of this priority class. This is the actual priority that pods receive when they have the name of this class in their pod spec.
     */
    value?: number | null;
}
/**
 * PriorityClassList is a collection of priority classes.
 */
export interface PriorityClassList extends AdditionalDataHolder, Parsable {
    /**
     * Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
     */
    additionalData?: Record<string, unknown>;
    /**
     * APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
     */
    apiVersion?: string | null;
    /**
     * items is the list of PriorityClasses
     */
    items?: PriorityClass[] | null;
    /**
     * Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
     */
    kind?: string | null;
    /**
     * ListMeta describes metadata that synthetic resources must have, including lists and various status objects. A resource may have only one of {ObjectMeta, ListMeta}.
     */
    metadata?: ListMeta | null;
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializePriorityClass(writer: SerializationWriter, priorityClass: Partial<PriorityClass> | undefined | null = {}) : void {
    if (priorityClass) {
        writer.writeStringValue("apiVersion", priorityClass.apiVersion);
        writer.writeStringValue("description", priorityClass.description);
        writer.writeBooleanValue("globalDefault", priorityClass.globalDefault);
        writer.writeStringValue("kind", priorityClass.kind);
        writer.writeObjectValue<ObjectMeta>("metadata", priorityClass.metadata, serializeObjectMeta);
        writer.writeStringValue("preemptionPolicy", priorityClass.preemptionPolicy);
        writer.writeNumberValue("value", priorityClass.value);
        writer.writeAdditionalData(priorityClass.additionalData);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializePriorityClassList(writer: SerializationWriter, priorityClassList: Partial<PriorityClassList> | undefined | null = {}) : void {
    if (priorityClassList) {
        writer.writeStringValue("apiVersion", priorityClassList.apiVersion);
        writer.writeCollectionOfObjectValues<PriorityClass>("items", priorityClassList.items, serializePriorityClass);
        writer.writeStringValue("kind", priorityClassList.kind);
        writer.writeObjectValue<ListMeta>("metadata", priorityClassList.metadata, serializeListMeta);
        writer.writeAdditionalData(priorityClassList.additionalData);
    }
}
/* tslint:enable */
/* eslint-enable */
