/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createAPIResourceListFromDiscriminatorValue, type APIResourceList } from '../../../models/apimachinery/pkg/apis/meta/v1/index.js';
// @ts-ignore
import { IngressclassesRequestBuilderNavigationMetadata, IngressclassesRequestBuilderRequestsMetadata, type IngressclassesRequestBuilder } from './ingressclasses/index.js';
// @ts-ignore
import { IngressesRequestBuilderRequestsMetadata, type IngressesRequestBuilder } from './ingresses/index.js';
// @ts-ignore
import { IpaddressesRequestBuilderNavigationMetadata, IpaddressesRequestBuilderRequestsMetadata, type IpaddressesRequestBuilder } from './ipaddresses/index.js';
// @ts-ignore
import { NamespacesRequestBuilderNavigationMetadata, type NamespacesRequestBuilder } from './namespaces/index.js';
// @ts-ignore
import { NetworkpoliciesRequestBuilderRequestsMetadata, type NetworkpoliciesRequestBuilder } from './networkpolicies/index.js';
// @ts-ignore
import { ServicecidrsRequestBuilderNavigationMetadata, ServicecidrsRequestBuilderRequestsMetadata, type ServicecidrsRequestBuilder } from './servicecidrs/index.js';
// @ts-ignore
import { type WatchRequestBuilder, WatchRequestBuilderNavigationMetadata } from './watch/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /apis/networking.k8s.io/v1/
 */
export interface V1RequestBuilder extends BaseRequestBuilder<V1RequestBuilder> {
    /**
     * The ingressclasses property
     */
    get ingressclasses(): IngressclassesRequestBuilder;
    /**
     * The ingresses property
     */
    get ingresses(): IngressesRequestBuilder;
    /**
     * The ipaddresses property
     */
    get ipaddresses(): IpaddressesRequestBuilder;
    /**
     * The namespaces property
     */
    get namespaces(): NamespacesRequestBuilder;
    /**
     * The networkpolicies property
     */
    get networkpolicies(): NetworkpoliciesRequestBuilder;
    /**
     * The servicecidrs property
     */
    get servicecidrs(): ServicecidrsRequestBuilder;
    /**
     * The watch property
     */
    get watch(): WatchRequestBuilder;
    /**
     * get available resources
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<APIResourceList>}
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<APIResourceList | undefined>;
    /**
     * get available resources
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const V1RequestBuilderUriTemplate = "{+baseurl}/apis/networking.k8s.io/v1/";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const V1RequestBuilderNavigationMetadata: Record<Exclude<keyof V1RequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    ingressclasses: {
        requestsMetadata: IngressclassesRequestBuilderRequestsMetadata,
        navigationMetadata: IngressclassesRequestBuilderNavigationMetadata,
    },
    ingresses: {
        requestsMetadata: IngressesRequestBuilderRequestsMetadata,
    },
    ipaddresses: {
        requestsMetadata: IpaddressesRequestBuilderRequestsMetadata,
        navigationMetadata: IpaddressesRequestBuilderNavigationMetadata,
    },
    namespaces: {
        navigationMetadata: NamespacesRequestBuilderNavigationMetadata,
    },
    networkpolicies: {
        requestsMetadata: NetworkpoliciesRequestBuilderRequestsMetadata,
    },
    servicecidrs: {
        requestsMetadata: ServicecidrsRequestBuilderRequestsMetadata,
        navigationMetadata: ServicecidrsRequestBuilderNavigationMetadata,
    },
    watch: {
        navigationMetadata: WatchRequestBuilderNavigationMetadata,
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const V1RequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: V1RequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        adapterMethodName: "send",
        responseBodyFactory:  createAPIResourceListFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
