/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { LocalsubjectaccessreviewsRequestBuilderRequestsMetadata, type LocalsubjectaccessreviewsRequestBuilder } from './localsubjectaccessreviews/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /apis/authorization.k8s.io/v1/namespaces/{namespace}
 */
export interface WithNamespaceItemRequestBuilder extends BaseRequestBuilder<WithNamespaceItemRequestBuilder> {
    /**
     * The localsubjectaccessreviews property
     */
    get localsubjectaccessreviews(): LocalsubjectaccessreviewsRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const WithNamespaceItemRequestBuilderUriTemplate = "{+baseurl}/apis/authorization.k8s.io/v1/namespaces/{namespace}";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const WithNamespaceItemRequestBuilderNavigationMetadata: Record<Exclude<keyof WithNamespaceItemRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    localsubjectaccessreviews: {
        requestsMetadata: LocalsubjectaccessreviewsRequestBuilderRequestsMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
