/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { ControllerrevisionsRequestBuilderNavigationMetadata, ControllerrevisionsRequestBuilderRequestsMetadata, type ControllerrevisionsRequestBuilder } from './controllerrevisions/index.js';
// @ts-ignore
import { DaemonsetsRequestBuilderNavigationMetadata, DaemonsetsRequestBuilderRequestsMetadata, type DaemonsetsRequestBuilder } from './daemonsets/index.js';
// @ts-ignore
import { DeploymentsRequestBuilderNavigationMetadata, DeploymentsRequestBuilderRequestsMetadata, type DeploymentsRequestBuilder } from './deployments/index.js';
// @ts-ignore
import { ReplicasetsRequestBuilderNavigationMetadata, ReplicasetsRequestBuilderRequestsMetadata, type ReplicasetsRequestBuilder } from './replicasets/index.js';
// @ts-ignore
import { StatefulsetsRequestBuilderNavigationMetadata, StatefulsetsRequestBuilderRequestsMetadata, type StatefulsetsRequestBuilder } from './statefulsets/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /apis/apps/v1/namespaces/{namespace}
 */
export interface WithNamespaceItemRequestBuilder extends BaseRequestBuilder<WithNamespaceItemRequestBuilder> {
    /**
     * The controllerrevisions property
     */
    get controllerrevisions(): ControllerrevisionsRequestBuilder;
    /**
     * The daemonsets property
     */
    get daemonsets(): DaemonsetsRequestBuilder;
    /**
     * The deployments property
     */
    get deployments(): DeploymentsRequestBuilder;
    /**
     * The replicasets property
     */
    get replicasets(): ReplicasetsRequestBuilder;
    /**
     * The statefulsets property
     */
    get statefulsets(): StatefulsetsRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const WithNamespaceItemRequestBuilderUriTemplate = "{+baseurl}/apis/apps/v1/namespaces/{namespace}";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const WithNamespaceItemRequestBuilderNavigationMetadata: Record<Exclude<keyof WithNamespaceItemRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    controllerrevisions: {
        requestsMetadata: ControllerrevisionsRequestBuilderRequestsMetadata,
        navigationMetadata: ControllerrevisionsRequestBuilderNavigationMetadata,
    },
    daemonsets: {
        requestsMetadata: DaemonsetsRequestBuilderRequestsMetadata,
        navigationMetadata: DaemonsetsRequestBuilderNavigationMetadata,
    },
    deployments: {
        requestsMetadata: DeploymentsRequestBuilderRequestsMetadata,
        navigationMetadata: DeploymentsRequestBuilderNavigationMetadata,
    },
    replicasets: {
        requestsMetadata: ReplicasetsRequestBuilderRequestsMetadata,
        navigationMetadata: ReplicasetsRequestBuilderNavigationMetadata,
    },
    statefulsets: {
        requestsMetadata: StatefulsetsRequestBuilderRequestsMetadata,
        navigationMetadata: StatefulsetsRequestBuilderNavigationMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
