/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /openid/v1/jwks/
 */
export interface JwksRequestBuilder extends BaseRequestBuilder<JwksRequestBuilder> {
    /**
     * get service account issuer OpenID JSON Web Key Set (contains public token verification keys)
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<string>}
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<string | undefined>;
    /**
     * get service account issuer OpenID JSON Web Key Set (contains public token verification keys)
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const JwksRequestBuilderUriTemplate = "{+baseurl}/openid/v1/jwks/";
/**
 * Metadata for all the requests in the request builder.
 */
export const JwksRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: JwksRequestBuilderUriTemplate,
        responseBodyContentType: "application/jwk-set+json",
        adapterMethodName: "sendPrimitive",
        responseBodyFactory:  "string",
    },
};
/* tslint:enable */
/* eslint-enable */
