/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { DeviceclassesRequestBuilderNavigationMetadata, DeviceclassesRequestBuilderRequestsMetadata, type DeviceclassesRequestBuilder } from './deviceclasses/index.js';
// @ts-ignore
import { NamespacesRequestBuilderNavigationMetadata, type NamespacesRequestBuilder } from './namespaces/index.js';
// @ts-ignore
import { ResourceclaimsRequestBuilderRequestsMetadata, type ResourceclaimsRequestBuilder } from './resourceclaims/index.js';
// @ts-ignore
import { ResourceclaimtemplatesRequestBuilderRequestsMetadata, type ResourceclaimtemplatesRequestBuilder } from './resourceclaimtemplates/index.js';
// @ts-ignore
import { ResourceslicesRequestBuilderNavigationMetadata, ResourceslicesRequestBuilderRequestsMetadata, type ResourceslicesRequestBuilder } from './resourceslices/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /apis/resource.k8s.io/v1beta1/watch
 */
export interface WatchRequestBuilder extends BaseRequestBuilder<WatchRequestBuilder> {
    /**
     * The deviceclasses property
     */
    get deviceclasses(): DeviceclassesRequestBuilder;
    /**
     * The namespaces property
     */
    get namespaces(): NamespacesRequestBuilder;
    /**
     * The resourceclaims property
     */
    get resourceclaims(): ResourceclaimsRequestBuilder;
    /**
     * The resourceclaimtemplates property
     */
    get resourceclaimtemplates(): ResourceclaimtemplatesRequestBuilder;
    /**
     * The resourceslices property
     */
    get resourceslices(): ResourceslicesRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const WatchRequestBuilderUriTemplate = "{+baseurl}/apis/resource.k8s.io/v1beta1/watch";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const WatchRequestBuilderNavigationMetadata: Record<Exclude<keyof WatchRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    deviceclasses: {
        requestsMetadata: DeviceclassesRequestBuilderRequestsMetadata,
        navigationMetadata: DeviceclassesRequestBuilderNavigationMetadata,
    },
    namespaces: {
        navigationMetadata: NamespacesRequestBuilderNavigationMetadata,
    },
    resourceclaims: {
        requestsMetadata: ResourceclaimsRequestBuilderRequestsMetadata,
    },
    resourceclaimtemplates: {
        requestsMetadata: ResourceclaimtemplatesRequestBuilderRequestsMetadata,
    },
    resourceslices: {
        requestsMetadata: ResourceslicesRequestBuilderRequestsMetadata,
        navigationMetadata: ResourceslicesRequestBuilderNavigationMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
