/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createAPIResourceListFromDiscriminatorValue, type APIResourceList } from '../../../models/apimachinery/pkg/apis/meta/v1/index.js';
// @ts-ignore
import { NamespacesRequestBuilderNavigationMetadata, type NamespacesRequestBuilder } from './namespaces/index.js';
// @ts-ignore
import { SelfsubjectaccessreviewsRequestBuilderRequestsMetadata, type SelfsubjectaccessreviewsRequestBuilder } from './selfsubjectaccessreviews/index.js';
// @ts-ignore
import { SelfsubjectrulesreviewsRequestBuilderRequestsMetadata, type SelfsubjectrulesreviewsRequestBuilder } from './selfsubjectrulesreviews/index.js';
// @ts-ignore
import { SubjectaccessreviewsRequestBuilderRequestsMetadata, type SubjectaccessreviewsRequestBuilder } from './subjectaccessreviews/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /apis/authorization.k8s.io/v1/
 */
export interface V1RequestBuilder extends BaseRequestBuilder<V1RequestBuilder> {
    /**
     * The namespaces property
     */
    get namespaces(): NamespacesRequestBuilder;
    /**
     * The selfsubjectaccessreviews property
     */
    get selfsubjectaccessreviews(): SelfsubjectaccessreviewsRequestBuilder;
    /**
     * The selfsubjectrulesreviews property
     */
    get selfsubjectrulesreviews(): SelfsubjectrulesreviewsRequestBuilder;
    /**
     * The subjectaccessreviews property
     */
    get subjectaccessreviews(): SubjectaccessreviewsRequestBuilder;
    /**
     * get available resources
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<APIResourceList>}
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<APIResourceList | undefined>;
    /**
     * get available resources
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const V1RequestBuilderUriTemplate = "{+baseurl}/apis/authorization.k8s.io/v1/";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const V1RequestBuilderNavigationMetadata: Record<Exclude<keyof V1RequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    namespaces: {
        navigationMetadata: NamespacesRequestBuilderNavigationMetadata,
    },
    selfsubjectaccessreviews: {
        requestsMetadata: SelfsubjectaccessreviewsRequestBuilderRequestsMetadata,
    },
    selfsubjectrulesreviews: {
        requestsMetadata: SelfsubjectrulesreviewsRequestBuilderRequestsMetadata,
    },
    subjectaccessreviews: {
        requestsMetadata: SubjectaccessreviewsRequestBuilderRequestsMetadata,
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const V1RequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: V1RequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        adapterMethodName: "send",
        responseBodyFactory:  createAPIResourceListFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
