/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { CsidriversRequestBuilderNavigationMetadata, CsidriversRequestBuilderRequestsMetadata, type CsidriversRequestBuilder } from './csidrivers/index.js';
// @ts-ignore
import { CsinodesRequestBuilderNavigationMetadata, CsinodesRequestBuilderRequestsMetadata, type CsinodesRequestBuilder } from './csinodes/index.js';
// @ts-ignore
import { CsistoragecapacitiesRequestBuilderRequestsMetadata, type CsistoragecapacitiesRequestBuilder } from './csistoragecapacities/index.js';
// @ts-ignore
import { NamespacesRequestBuilderNavigationMetadata, type NamespacesRequestBuilder } from './namespaces/index.js';
// @ts-ignore
import { StorageclassesRequestBuilderNavigationMetadata, StorageclassesRequestBuilderRequestsMetadata, type StorageclassesRequestBuilder } from './storageclasses/index.js';
// @ts-ignore
import { type VolumeattachmentsRequestBuilder, VolumeattachmentsRequestBuilderNavigationMetadata, VolumeattachmentsRequestBuilderRequestsMetadata } from './volumeattachments/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /apis/storage.k8s.io/v1/watch
 */
export interface WatchRequestBuilder extends BaseRequestBuilder<WatchRequestBuilder> {
    /**
     * The csidrivers property
     */
    get csidrivers(): CsidriversRequestBuilder;
    /**
     * The csinodes property
     */
    get csinodes(): CsinodesRequestBuilder;
    /**
     * The csistoragecapacities property
     */
    get csistoragecapacities(): CsistoragecapacitiesRequestBuilder;
    /**
     * The namespaces property
     */
    get namespaces(): NamespacesRequestBuilder;
    /**
     * The storageclasses property
     */
    get storageclasses(): StorageclassesRequestBuilder;
    /**
     * The volumeattachments property
     */
    get volumeattachments(): VolumeattachmentsRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const WatchRequestBuilderUriTemplate = "{+baseurl}/apis/storage.k8s.io/v1/watch";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const WatchRequestBuilderNavigationMetadata: Record<Exclude<keyof WatchRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    csidrivers: {
        requestsMetadata: CsidriversRequestBuilderRequestsMetadata,
        navigationMetadata: CsidriversRequestBuilderNavigationMetadata,
    },
    csinodes: {
        requestsMetadata: CsinodesRequestBuilderRequestsMetadata,
        navigationMetadata: CsinodesRequestBuilderNavigationMetadata,
    },
    csistoragecapacities: {
        requestsMetadata: CsistoragecapacitiesRequestBuilderRequestsMetadata,
    },
    namespaces: {
        navigationMetadata: NamespacesRequestBuilderNavigationMetadata,
    },
    storageclasses: {
        requestsMetadata: StorageclassesRequestBuilderRequestsMetadata,
        navigationMetadata: StorageclassesRequestBuilderNavigationMetadata,
    },
    volumeattachments: {
        requestsMetadata: VolumeattachmentsRequestBuilderRequestsMetadata,
        navigationMetadata: VolumeattachmentsRequestBuilderNavigationMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
