/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { FlowschemasRequestBuilderNavigationMetadata, FlowschemasRequestBuilderRequestsMetadata, type FlowschemasRequestBuilder } from './flowschemas/index.js';
// @ts-ignore
import { PrioritylevelconfigurationsRequestBuilderNavigationMetadata, PrioritylevelconfigurationsRequestBuilderRequestsMetadata, type PrioritylevelconfigurationsRequestBuilder } from './prioritylevelconfigurations/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /apis/flowcontrol.apiserver.k8s.io/v1/watch
 */
export interface WatchRequestBuilder extends BaseRequestBuilder<WatchRequestBuilder> {
    /**
     * The flowschemas property
     */
    get flowschemas(): FlowschemasRequestBuilder;
    /**
     * The prioritylevelconfigurations property
     */
    get prioritylevelconfigurations(): PrioritylevelconfigurationsRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const WatchRequestBuilderUriTemplate = "{+baseurl}/apis/flowcontrol.apiserver.k8s.io/v1/watch";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const WatchRequestBuilderNavigationMetadata: Record<Exclude<keyof WatchRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    flowschemas: {
        requestsMetadata: FlowschemasRequestBuilderRequestsMetadata,
        navigationMetadata: FlowschemasRequestBuilderNavigationMetadata,
    },
    prioritylevelconfigurations: {
        requestsMetadata: PrioritylevelconfigurationsRequestBuilderRequestsMetadata,
        navigationMetadata: PrioritylevelconfigurationsRequestBuilderNavigationMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
