/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { RolebindingsRequestBuilderNavigationMetadata, RolebindingsRequestBuilderRequestsMetadata, type RolebindingsRequestBuilder } from './rolebindings/index.js';
// @ts-ignore
import { RolesRequestBuilderNavigationMetadata, RolesRequestBuilderRequestsMetadata, type RolesRequestBuilder } from './roles/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /apis/rbac.authorization.k8s.io/v1/namespaces/{namespace}
 */
export interface WithNamespaceItemRequestBuilder extends BaseRequestBuilder<WithNamespaceItemRequestBuilder> {
    /**
     * The rolebindings property
     */
    get rolebindings(): RolebindingsRequestBuilder;
    /**
     * The roles property
     */
    get roles(): RolesRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const WithNamespaceItemRequestBuilderUriTemplate = "{+baseurl}/apis/rbac.authorization.k8s.io/v1/namespaces/{namespace}";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const WithNamespaceItemRequestBuilderNavigationMetadata: Record<Exclude<keyof WithNamespaceItemRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    rolebindings: {
        requestsMetadata: RolebindingsRequestBuilderRequestsMetadata,
        navigationMetadata: RolebindingsRequestBuilderNavigationMetadata,
    },
    roles: {
        requestsMetadata: RolesRequestBuilderRequestsMetadata,
        navigationMetadata: RolesRequestBuilderNavigationMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
