/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { IngressclassesRequestBuilderNavigationMetadata, IngressclassesRequestBuilderRequestsMetadata, type IngressclassesRequestBuilder } from './ingressclasses/index.js';
// @ts-ignore
import { IngressesRequestBuilderRequestsMetadata, type IngressesRequestBuilder } from './ingresses/index.js';
// @ts-ignore
import { IpaddressesRequestBuilderNavigationMetadata, IpaddressesRequestBuilderRequestsMetadata, type IpaddressesRequestBuilder } from './ipaddresses/index.js';
// @ts-ignore
import { NamespacesRequestBuilderNavigationMetadata, type NamespacesRequestBuilder } from './namespaces/index.js';
// @ts-ignore
import { NetworkpoliciesRequestBuilderRequestsMetadata, type NetworkpoliciesRequestBuilder } from './networkpolicies/index.js';
// @ts-ignore
import { ServicecidrsRequestBuilderNavigationMetadata, ServicecidrsRequestBuilderRequestsMetadata, type ServicecidrsRequestBuilder } from './servicecidrs/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /apis/networking.k8s.io/v1/watch
 */
export interface WatchRequestBuilder extends BaseRequestBuilder<WatchRequestBuilder> {
    /**
     * The ingressclasses property
     */
    get ingressclasses(): IngressclassesRequestBuilder;
    /**
     * The ingresses property
     */
    get ingresses(): IngressesRequestBuilder;
    /**
     * The ipaddresses property
     */
    get ipaddresses(): IpaddressesRequestBuilder;
    /**
     * The namespaces property
     */
    get namespaces(): NamespacesRequestBuilder;
    /**
     * The networkpolicies property
     */
    get networkpolicies(): NetworkpoliciesRequestBuilder;
    /**
     * The servicecidrs property
     */
    get servicecidrs(): ServicecidrsRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const WatchRequestBuilderUriTemplate = "{+baseurl}/apis/networking.k8s.io/v1/watch";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const WatchRequestBuilderNavigationMetadata: Record<Exclude<keyof WatchRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    ingressclasses: {
        requestsMetadata: IngressclassesRequestBuilderRequestsMetadata,
        navigationMetadata: IngressclassesRequestBuilderNavigationMetadata,
    },
    ingresses: {
        requestsMetadata: IngressesRequestBuilderRequestsMetadata,
    },
    ipaddresses: {
        requestsMetadata: IpaddressesRequestBuilderRequestsMetadata,
        navigationMetadata: IpaddressesRequestBuilderNavigationMetadata,
    },
    namespaces: {
        navigationMetadata: NamespacesRequestBuilderNavigationMetadata,
    },
    networkpolicies: {
        requestsMetadata: NetworkpoliciesRequestBuilderRequestsMetadata,
    },
    servicecidrs: {
        requestsMetadata: ServicecidrsRequestBuilderRequestsMetadata,
        navigationMetadata: ServicecidrsRequestBuilderNavigationMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
