/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { IngressesRequestBuilderNavigationMetadata, IngressesRequestBuilderRequestsMetadata, type IngressesRequestBuilder } from './ingresses/index.js';
// @ts-ignore
import { NetworkpoliciesRequestBuilderNavigationMetadata, NetworkpoliciesRequestBuilderRequestsMetadata, type NetworkpoliciesRequestBuilder } from './networkpolicies/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /apis/networking.k8s.io/v1/namespaces/{namespace}
 */
export interface WithNamespaceItemRequestBuilder extends BaseRequestBuilder<WithNamespaceItemRequestBuilder> {
    /**
     * The ingresses property
     */
    get ingresses(): IngressesRequestBuilder;
    /**
     * The networkpolicies property
     */
    get networkpolicies(): NetworkpoliciesRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const WithNamespaceItemRequestBuilderUriTemplate = "{+baseurl}/apis/networking.k8s.io/v1/namespaces/{namespace}";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const WithNamespaceItemRequestBuilderNavigationMetadata: Record<Exclude<keyof WithNamespaceItemRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    ingresses: {
        requestsMetadata: IngressesRequestBuilderRequestsMetadata,
        navigationMetadata: IngressesRequestBuilderNavigationMetadata,
    },
    networkpolicies: {
        requestsMetadata: NetworkpoliciesRequestBuilderRequestsMetadata,
        navigationMetadata: NetworkpoliciesRequestBuilderNavigationMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
