/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createInfoFromDiscriminatorValue, type Info } from '../models/apimachinery/pkg/version/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /version/
 */
export interface VersionRequestBuilder extends BaseRequestBuilder<VersionRequestBuilder> {
    /**
     * get the code version
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<Info>}
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<Info | undefined>;
    /**
     * get the code version
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const VersionRequestBuilderUriTemplate = "{+baseurl}/version/";
/**
 * Metadata for all the requests in the request builder.
 */
export const VersionRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: VersionRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        adapterMethodName: "send",
        responseBodyFactory:  createInfoFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
