/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { NamespacesRequestBuilderNavigationMetadata, type NamespacesRequestBuilder } from './namespaces/index.js';
// @ts-ignore
import { PoddisruptionbudgetsRequestBuilderRequestsMetadata, type PoddisruptionbudgetsRequestBuilder } from './poddisruptionbudgets/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /apis/policy/v1/watch
 */
export interface WatchRequestBuilder extends BaseRequestBuilder<WatchRequestBuilder> {
    /**
     * The namespaces property
     */
    get namespaces(): NamespacesRequestBuilder;
    /**
     * The poddisruptionbudgets property
     */
    get poddisruptionbudgets(): PoddisruptionbudgetsRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const WatchRequestBuilderUriTemplate = "{+baseurl}/apis/policy/v1/watch";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const WatchRequestBuilderNavigationMetadata: Record<Exclude<keyof WatchRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    namespaces: {
        navigationMetadata: NamespacesRequestBuilderNavigationMetadata,
    },
    poddisruptionbudgets: {
        requestsMetadata: PoddisruptionbudgetsRequestBuilderRequestsMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
