/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createAPIResourceListFromDiscriminatorValue, type APIResourceList } from '../../../models/apimachinery/pkg/apis/meta/v1/index.js';
// @ts-ignore
import { ControllerrevisionsRequestBuilderRequestsMetadata, type ControllerrevisionsRequestBuilder } from './controllerrevisions/index.js';
// @ts-ignore
import { DaemonsetsRequestBuilderRequestsMetadata, type DaemonsetsRequestBuilder } from './daemonsets/index.js';
// @ts-ignore
import { DeploymentsRequestBuilderRequestsMetadata, type DeploymentsRequestBuilder } from './deployments/index.js';
// @ts-ignore
import { NamespacesRequestBuilderNavigationMetadata, type NamespacesRequestBuilder } from './namespaces/index.js';
// @ts-ignore
import { ReplicasetsRequestBuilderRequestsMetadata, type ReplicasetsRequestBuilder } from './replicasets/index.js';
// @ts-ignore
import { StatefulsetsRequestBuilderRequestsMetadata, type StatefulsetsRequestBuilder } from './statefulsets/index.js';
// @ts-ignore
import { type WatchRequestBuilder, WatchRequestBuilderNavigationMetadata } from './watch/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /apis/apps/v1/
 */
export interface V1RequestBuilder extends BaseRequestBuilder<V1RequestBuilder> {
    /**
     * The controllerrevisions property
     */
    get controllerrevisions(): ControllerrevisionsRequestBuilder;
    /**
     * The daemonsets property
     */
    get daemonsets(): DaemonsetsRequestBuilder;
    /**
     * The deployments property
     */
    get deployments(): DeploymentsRequestBuilder;
    /**
     * The namespaces property
     */
    get namespaces(): NamespacesRequestBuilder;
    /**
     * The replicasets property
     */
    get replicasets(): ReplicasetsRequestBuilder;
    /**
     * The statefulsets property
     */
    get statefulsets(): StatefulsetsRequestBuilder;
    /**
     * The watch property
     */
    get watch(): WatchRequestBuilder;
    /**
     * get available resources
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<APIResourceList>}
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<APIResourceList | undefined>;
    /**
     * get available resources
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const V1RequestBuilderUriTemplate = "{+baseurl}/apis/apps/v1/";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const V1RequestBuilderNavigationMetadata: Record<Exclude<keyof V1RequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    controllerrevisions: {
        requestsMetadata: ControllerrevisionsRequestBuilderRequestsMetadata,
    },
    daemonsets: {
        requestsMetadata: DaemonsetsRequestBuilderRequestsMetadata,
    },
    deployments: {
        requestsMetadata: DeploymentsRequestBuilderRequestsMetadata,
    },
    namespaces: {
        navigationMetadata: NamespacesRequestBuilderNavigationMetadata,
    },
    replicasets: {
        requestsMetadata: ReplicasetsRequestBuilderRequestsMetadata,
    },
    statefulsets: {
        requestsMetadata: StatefulsetsRequestBuilderRequestsMetadata,
    },
    watch: {
        navigationMetadata: WatchRequestBuilderNavigationMetadata,
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const V1RequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: V1RequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        adapterMethodName: "send",
        responseBodyFactory:  createAPIResourceListFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
