/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { EventsRequestBuilderNavigationMetadata, EventsRequestBuilderRequestsMetadata, type EventsRequestBuilder } from './events/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /apis/events.k8s.io/v1/namespaces/{namespace}
 */
export interface WithNamespaceItemRequestBuilder extends BaseRequestBuilder<WithNamespaceItemRequestBuilder> {
    /**
     * The events property
     */
    get events(): EventsRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const WithNamespaceItemRequestBuilderUriTemplate = "{+baseurl}/apis/events.k8s.io/v1/namespaces/{namespace}";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const WithNamespaceItemRequestBuilderNavigationMetadata: Record<Exclude<keyof WithNamespaceItemRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    events: {
        requestsMetadata: EventsRequestBuilderRequestsMetadata,
        navigationMetadata: EventsRequestBuilderNavigationMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
