/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { ClustertrustbundlesRequestBuilderNavigationMetadata, ClustertrustbundlesRequestBuilderRequestsMetadata, type ClustertrustbundlesRequestBuilder } from './clustertrustbundles/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /apis/certificates.k8s.io/v1alpha1/watch
 */
export interface WatchRequestBuilder extends BaseRequestBuilder<WatchRequestBuilder> {
    /**
     * The clustertrustbundles property
     */
    get clustertrustbundles(): ClustertrustbundlesRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const WatchRequestBuilderUriTemplate = "{+baseurl}/apis/certificates.k8s.io/v1alpha1/watch";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const WatchRequestBuilderNavigationMetadata: Record<Exclude<keyof WatchRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    clustertrustbundles: {
        requestsMetadata: ClustertrustbundlesRequestBuilderRequestsMetadata,
        navigationMetadata: ClustertrustbundlesRequestBuilderNavigationMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
